apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../services/leeroy-app/overlays/staging
- ../../services/leeroy-web/overlays/staging
commonLabels:
  project: leeroy
  env: staging